[package]
name = "ffly-rs"
version = "0.0.0"
edition = "2021"
description = "An \"blazingly\" fast key-value pair database without bloat written in rust"
license = "MIT"


[dependencies]
tokio = { version = "1.20.1", features = ["full"] }
