[package]
name = "ffly-rs"
version = "0.0.1"
edition = "2021"
description = "A rust utility library for the Firefly key-value pair database."
license = "MIT"


[dependencies]
tokio = { version = "1.20.1", features = ["full"] }
