[package]
name = "ffly"
version = "0.0.0-dev"
edition = "2021"
description = "An \"blazingly\" fast key-value pair database without bloat written in rust"
license = "MIT"

[dependencies]
anyhow = "1.0.59"
bincode = "1.3.3"
log = "0.4.17"
pretty_env_logger = "0.4.0"
strum = "0.24.1"
strum_macros = "0.24.2"
tokio = { version = "1.20.1", features = ["full"] }
