[package]
name = "rest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.0"
ffly-rs = "0.0.6"
serde = { version = "1.0.188", features = ["derive"] }
